# Generated by Django 4.2.6 on 2023-10-22 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_newsletter_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newsletter.letter', verbose_name='Письмо рассылки'),
        ),
    ]
