# Generated by Django 4.2.6 on 2023-10-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_newsletter_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nllogs',
            name='status',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('CRE', 'Создана'), ('ONG', 'Запушена'), ('END', 'Завершена')], default='CRE', max_length=30, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='NLStatus',
        ),
    ]
