# Generated by Django 4.2.6 on 2023-10-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_remove_nllogs_status_alter_newsletter_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='end',
            field=models.DateField(verbose_name='по'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='start',
            field=models.DateField(verbose_name='с'),
        ),
    ]
