# Generated by Django 4.2.6 on 2023-10-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='Avatar')),
            ],
            options={
                'verbose_name': 'studentik',
                'verbose_name_plural': 'studentiki',
                'ordering': ('last_name',),
            },
        ),
    ]
