# Generated by Django 4.2.6 on 2023-10-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_product_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
