# Generated by Django 4.2.6 on 2023-10-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_creation_date_product_last_change_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_change_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
