# Generated by Django 4.2.6 on 2023-10-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.CharField(max_length=100, verbose_name='Ссылка')),
                ('text', models.TextField(verbose_name='Текст записи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogpost/', verbose_name='Превью')),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('published', models.BooleanField()),
                ('view_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ('id', 'title'),
            },
        ),
    ]
